name: Deploy to Hetzner VPS

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main  # Adjust if your deployment branch is named differently (e.g., master)

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest # Use the latest Ubuntu runner from GitHub

    steps:
    # 1. Check out the repository code onto the runner
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true # Important: Ensure Git LFS files are checked out correctly

    # 2. SSH into the VPS and run deployment commands
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master # Popular action for SSH commands
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }} # Use secret or default to 22
        script: |
          set -e # Exit script immediately if any command fails
          cd /home/deployuser/lead-trade-dashboard # Navigate to the app directory
          git pull origin main # Pull the latest changes from the specified branch
          git lfs pull # Pull any updated LFS file content
          # Activate venv and install/update dependencies
          # Using '.' as the POSIX-compliant way to source in potentially basic shells
          . venv/bin/activate
          pip install -r requirements.txt
          echo "Dependencies installed."
          # Restart the Streamlit service using passwordless sudo
          sudo /bin/systemctl restart streamlit-app.service # Use full path for sudo
          echo "Streamlit service restarted."
          echo "Deployment successful!"
